#include<string>
#include<iostream>
#include"Cell.h"
#include"string.h"
#include<vector>
#ifndef CONNECTFOURABSTRACT_H
#define CONNECTFOURABSTRACT_H

namespace my_namespace
{


class ConnectFourAbstract{
	protected:
			vector<int> moves;//YAPILAN HER HAMLE BURAYA KAYDEDILECEK GERI ALIRKEN KULLANILACAK 
			string file_name;//KULLANICIDAN ALINAN KOMUTA GORE BU DEGISKEN KAYDEDILECEK YA DA OKUNACAK DOSYANIN ADINI TUTACAK
			virtual int move();//KULLANICIDAN HAMLE ALACAK VE DUNDURECEK
			int rowSize;//SATIR SAYISI
			int columnSize;//SUTUN SAYISI	
			int row;//HUCRENIN BULUNDUGU SATIRI TUTACAK	
			char column;//HUCRENIN POZISYONUNU TUTACAK(A,B,C,D,.....)	
			void play();//that plays computer
			void play(int& position,char sign);//that plAYS USER
			virtual void endGame(char sign);//OYUN BU FONKSÝYOLA BÝTECEK KAZANAN VARSA VEYA BERABERLÝK VARSA BÝLDÝRECEK
			virtual void change_to_lower(char Sign);//BU FONKSIYON OYUN BITTIKTEN SONRA KAZANAN DORTLUYU KUCULTUP YAZDIRACAK
			void player2player();//BU FONSIYON PLAYER TO PLAYER OYUNU OYNAYACAK
			void player2cpu();//BU FONKSIYON PLAYER TO CPU OYUNU PYNAYACAK
			char game_mod;//GAME MOD DEGISKENI
			void read_from_file() ;//BU FONSIYON KAYITLI OYUNU DOSYADAN OKUYACAK
			void write_to_file();//BU FONSIYON OYUN U FILE A YAZACAK
			const void one_object_game();//BIR OBJENIN OYUNU BUNUN IÇINDE OYNANACAK
			Cell** gameboard;//CELL SINIFININ NESNELERINI TUTAN DINAMIK ARRAY TANIMLADIM
			void show_current_board();//HAMLELER YAPILDIKTAN SONRADA YENI TABLOYU YAZDIRAN FONKSIYON
			bool game_end=false;//OYUN BITTIYSE BU DEGISKEN TRUE OLACAK 
			const void setGameMod();//GAME MOD U KULLANICIDAN ALIP ATAYACAK FONKSIYON
			const void setRowSize();//ROW SIZE I KULLANICIDAN ALIP ATAYCAK FONKSIYON
			const void setColumnSize();//COLMUN SIZE I KULLANICIDAN ALIP ATAYACK FONSKTIYON
			void play_undo();//UNDOGAME DE KULLNILACAK GERI ALMA FONKSIYONU
			const int currentwidth();//ROW  U GERI DONDUREN FONKSIYON
			const int currentheight();//COLUMN U GERI DONDURECCEK FONKSIYON
			int undo=0;//BU DEGISKENI UNDO YAOTIKTAN SONRA BI ONCEKI KULLANICIYA GEÇMESI ICIN TANIMLADIM//BU DEGISKENI KULANDIGIM FONKSIYONLARI OVERRRIDE ETMMEMEK ICIN BURDA TANIMLADIM

	public:
			void playGame();//KULLANICIDAN SIZE VE GAME MOD ALINACAK VE OYUN OYNANCAK//BU FONSIYONUN ICINDE PLAYER2PLAYER VE PLAYER2CPU FONKSIYONLARI CALISACAK

			
		
};
}
#endif
